### ISSUE TITLE
Include header issue

### ISSUE THREAD

**Issue by iceb0y** [curtismuntz/bazel_compilers#1]
There was an issue in c2309319105f993d6c88a7e0cf093af9ad08b33a . This should be similar to https://github.com/OpenLightingProject/ola/issues/1125 .

**Comment by curtismuntz** [comment]
I've upgrade linaro to 7.3.1 in #2 which should resolve this.

Thanks for the reminder!

**Comment by iceb0y** [comment]
Thanks!
